# Generated by Django 4.1.13 on 2024-04-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="student_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "my_collection",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
