# Generated by Django 5.0.4 on 2024-05-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_addional_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("skills", models.CharField(max_length=255)),
                ("age", models.CharField(max_length=255)),
                ("faculty", models.CharField(max_length=255)),
                ("disability", models.BooleanField(default=False)),
                ("grade", models.CharField(max_length=50)),
                ("cgpa", models.CharField(max_length=10)),
                (
                    "connect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
