# Generated by Django 5.0.4 on 2024-05-09 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_user_addional_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User_addional_data",
        ),
    ]
