# Generated by Django 5.0.4 on 2024-05-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
