# Generated by Django 5.0.4 on 2024-05-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_is_active_user_active_remove_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
