# Generated by Django 5.0.4 on 2024-05-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_remove_user_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new_password",
            field=models.CharField(default="", max_length=255),
        ),
    ]
