# Generated by Django 5.0.4 on 2024-05-13 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_user_new_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="new_password",
        ),
    ]
