POST http://127.0.0.1:8000/login/
Content-Type: application/json

{ "email": "hoo@gmail.com", "password": "ll665066" }
#### 
#######
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{"username":"hoo", "email": "hoo@gmail.com", "password": "ll665066" }

######
POST http://127.0.0.1:8000/change_password/
Content-Type: application/json

{"email": "yoo@gmail.com", "password": "000" , "new_password": "123"}

####
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token e4d1f16896422760479ecfad10713523ad8ccb3e
                    

{}

#######
POST http://127.0.0.1:8000/add_user/
Content-Type: application/json

{"username":"test", "email": "testt@gmail.com", "password": "ll665066" }
###########
GET http://127.0.0.1:8000/users/
Content-Type: application/json

############
POST http://127.0.0.1:8000/suspend_users/
Content-Type: application/json

{"email": "ahmed@gmail.com", "is_active": "False" }
###########
POST http://127.0.0.1:8000/logout/
Content-Type: application/json
Authorization: Token e4d1f16896422760479ecfad10713523ad8ccb3e

{}
##################

GET http://127.0.0.1:8000/accounts/reset/done/
Content-Type: application/json